service: openspot-instance-selector

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  profile: openspot
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  selector:
    handler: bin/selector


